swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  #! User Module
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  #! Transactions module
  /user/transactions:
    get: 
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Display monthly transaction
      description: API to display monthly transaction, by account
      produces:
      - application/json
      responses:
        "200":
          description: Successful retrieval of user transaction
          schema:
            type: array
            items:
              $ref: "#/definitions/Account"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}: 
    get: 
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Display transaction details
      description: API to display specific transaction
      parameters:
      - name: transactionId
        type : number
        in: path
        description : Id of the Transaction
        required: true
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TransactionDetails'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put : 
      security:
          - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction
      description: API to Update a Transaction's category and note
      parameters:
      - name: transactionId
        type : string
        in: path
        description : Id of the Transaction
        required: true
      - in: body
        name: body
        description: Fields to Update
        schema:
          $ref: '#/definitions/TransactionUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TransactionDetails'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error


  #! Definitions section
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  # Account definition
  Account:
    type: object
    properties:
      date:
        type: string
        pattern: "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$"
        description: Date of the transaction
      description: 
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance: 
        type: number
        description: Balance after the transaction
    required: 
      - date
      - description
      - amount
      - balance
  # Transaction definition
  TransactionDetails: 
    type: object
    properties:
      date:
        type: string
        pattern: "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}$"
        description: Date of the transaction
      description: 
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance: 
        type: number
        description: Balance after the transaction
      type: 
        type: string
        description: Type of the transaction
      category:
        type: string
        description: Category of the transaction
      note: 
        type: string
        description: Note of the transaction
  # TransactionUpdate definition
  TransactionUpdate: 
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      note: 
        type: string
        description: Updated note of the transaction
